services:
  web:
    build: .
    command: sh -c './wait-for-it.sh db:5432 -s -- 
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
      - ./fixtures:/app/fixtures
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=cilitran.settings
      - DATABASE_URL=postgres://database_admin:42700005049@db:5432/hotel
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hotel
      - POSTGRES_USER=database_admin
      - POSTGRES_PASSWORD=42700005049

volumes:
  postgres_data:
