# Generated by Django 5.1.1 on 2024-10-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_review_title_alter_hotel_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
    ]
