# Generated by Django 5.1.1 on 2024-10-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hotel_address_remove_place_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='postal_code',
        ),
    ]
